- .travis.yml
Add `rpm` package to `apt-get install` line in .travis.yml under the
`install` option.
Modify .travis.yml to include `before_deploy` & `deploy` options.
From this point all that needs to be done, is to generate an 
[Access Token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/), and [encrypt](http://docs.travis-ci.com/user/encryption-keys/) it via `travis encrypt "AccessToken"` and replacing `cJSUi9wKAjJ7LqPQ8UXnMfHoDYwow4lHqQnp+EGAle1BHrbwMYPinfQzzLXRy40rqFrF2b/t0qBsGNJRNGBhI65nSgJElLGsgyAkV3h31uvVop5T4f93eEcuFMPYG74UtUPwTPTmRLB1GxZumELvKgJyne7xF4JHTvUDlsQAqg0=`
in .travis.yml with the encrypted token echo'd out. 
Feel free to post an encrypted Access Token and I will revise my commits to include it instead.
If there is anything that isn't pragmatic or is …
> Setup automated Travis-CI Linux Deployments(#290)

- .travis.yml
Remove spaces in Access Token caused by copy+paste from github
Change `condition` to look for gcc-4.8
Stop using `$TRAVIS_TAG` to match files for deployment
> Fix Travis-CI Deployment(#342)

- .travis.yml
Add `file_glob: true` in .travis.yml
> Fix wildcard use in names for Travis Releases

- .travis.yml
Removed .deb, and .rpm packages from Travis Deployments due to failures addressed in #345. This is temporary assuming the issues are addressed in #89 & #224, or targeted distributions are changed.
> Remove .deb & .rpm packages from Travis Releases temporarily

- doc/COPYING.GPL
Resolves an rpmlint warning:
```
cdogs-sdl.x86_64: W: incorrect-fsf-address /usr/share/cdogs-sdl/doc/COPYING.GPL
The Free Software Foundation address in this file seems to be outdated or
misspelled.  Ask upstream to update the address, or if this is a license file,
possibly the entire file with a new copy available from the FSF.
```
> Updated COPYING.GPL

- COPYING
resolves an rpmlint warning at @openSUSE build service:
```
W: incorrect-fsf-address /usr/share/cdogs-sdl/doc/COPYING.GPL
The Free Software Foundation address in this file seems to be outdated or
misspelled.  Ask upstream to update the address, or if this is a license file,
possibly the entire file with a new copy available from the FSF.
```
> Updated GPL license text from current master template

- CMakeLists.txt
as it got hard-coded to `.` which also can't be fixed via a `cmake -DINSTALL_PREFIX=` parameter as you overwrite it with a hard-coded value later in the script.
> Fixed INSTALL_PREFIX for Linux

- src/cdogs/objs.c
Did an implementation of "Pickups in destroyed map objects" in https://github.com/cxong/cdogs-sdl/issues/367
But it does a gun drop with super low chance instead of an ammo drop.
> Pickups in map objects

- CMakeLists.txt
- src/cdogs/CMakeLists.txt
This is based on the patch from @akien-mga http://sophie.aero.jussieu.fr/distrib/Mageia/cauldron/i586/by-pkgid/8769c31df9dc9a5eebb81327ad39b0ba/files/1 but made configurable so it doesn't disturb anyone.
> Added USE_SHARED_ENET parameter for Linux distributions

- CMakeLists.txt
The DESTINATION parameter of INSTALL is a target directory, hence the
icons ends up in a subdirectory such as:
/usr/share/icons/hicolor/32x32/apps/cdogs-sdl.png/cdogs-icon.32.png
Change DESTINATION to the parent directory and rename the icon
cdogs-sdl.png. Result:
/usr/share/icons/hicolor/32x32/apps/cdogs-sdl.png
Signed-off-by: Antoine Musso <hashar@free.fr>
> Rename icon when installing them

- CMakeLists.txt
Add support for overriding where binaries get installed via the CMake
variable CDOGS_BIN_DIR. The reason is Debian policy 11.11 (Games)
requires to get them under /usr/games, hence the package would need a
way to override where binaries are installed.
Signed-off-by: Antoine Musso <hashar@free.fr>
> Let us change binary directory

- build/cmake/Copyright.txt
- build/cmake/FindSDL2.cmake
- build/cmake/FindSDL2_image.cmake
- build/cmake/FindSDL2_mixer.cmake
The source code for build/cmake/FindSDL2* comes from
https://github.com/clintbellanger/flare-engine/ by Justin Jacobs copied
in 2014 from CMake.  The source files referred a Copyright.txt which is
https://github.com/Kitware/CMake/blob/f2ec464fe030b562134f9b66a503735cca08f695/Copyright.txt
Copy the CMake Copyright.txt as it was in 2014 to
build/cmake/Copyright.txt
Update Copyrights statements for work by:
* Justin Jacobs on https://github.com/clintbellanger/flare-engine/
* Cong Xu here
Part of #89
> Fix copyright statements for build/cmake/Copyright

- .gitattributes
github and Debian "git buildpackage" create tarballs from the git
repository using "git archive". Exclude some of the files from the repo
by adding them to .gitattribute:
/.gitattributes
/.gitignore
/.travis.yml
/appveyor.yml
/appveyor.yml.cmake
/wiki*
Tested using:
git archive --worktree-attributes HEAD|tar -t
Signed-off-by: Antoine Musso <hashar@free.fr>
> Exclude files from generated tarballs

- build/linux/cdogs-sdl.appdata.xml
raw.github.com is deprecated and redirects to raw.githubusercontent.com.
Adjust the screenshot URL in build/linux/cdogs-sdl.appdata.xml
Signed-off-by: Antoine Musso <hashar@free.fr>
> Use raw.githubusercontent.com in appdata.xml

- src/cdogs/actors.c
- src/cdogs/mathc/README.md
- src/cdogs/mathc/mathc.c
- src/cdogs/mathc/mathc.h
- src/cdogs/utils.c
The value of `EPSILON_POS` was too large, and in combination with the new function for floating-point comparison, resulted in the actor getting stuck at the same position, because `TryMoveActor()` would return early when checking if the new position and the old position, considering them the same. Diagonal movements still worked, but horizontal/vertical movement were affected. This patch fix the issue by:
1. Not using `EPSILON_POS` and using the machine epsilon instead.
2. Updating the function for floating-point comparison in MATHC2 to look like the old one.
> Fix floating-point comparison

- src/player_select_menus.c
Currently, saving a new character crashes the game with a segmentation fault. This patch fixes this issue.
> Fix crash when creating new character.

- CMakeLists.txt
Enable [multiprocessor compiling](https://docs.microsoft.com/en-us/cpp/build/reference/mp-build-with-multiple-processes?view=vs-2019) on MSVC. Huge compilation time improvement.
> Enable multiprocessor compiling on MSVC

- src/cdogs/character.c
Fix issue #608 
Because `CSTRDUP` is a macro and not a function call, `CArrayGet` got called twice with different `rand()` value - first in memory allocation and then in copying. It meant that memory was reserved for other name than what was actually copied leading to potential buffer overflow.
In other words, `CSTRDUP` call got expanded to
```
CMALLOC(c->Hair, strlen(*(char **)CArrayGet(
&gPicManager.hairstyleNames,
rand() % gPicManager.hairstyleNames.size)) + 1);
strcpy(c->Hair, *(char **)CArrayGet(
&gPicManager.hairstyleNames,
rand() % gPicManager.hairstyleNames.size));
```
> Fix heap corruption with hair style name

- src/menu.c
Some weapons had a description longer than the text buffer (256 chars). This PR doubles the text buffer size and prevents overflow for longer strings. Just found this when starting the game for the first time and trying to select the Shotgun in the Sand campaign, the game crashed.
There is still a lot more code that uses strcpy and sprintf unchecked, and could cause crashes elsewhere (Just look at the compiler warnings)
> fix string overflow for long weapon descriptions

- CMakeLists.txt
The /usr/share/appdata/ path is deprecated and support will likely be
dropped completely in the future:
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location
> Install appdata files to metainfo directory

- src/cdogsed/osdialog/CMakeLists.txt
This defaults CMake to build the bundled osdialog as a static library.
This helps prevent problems in operating systems such as Gentoo Linux
which assume dynamic linking and subsequently install cdogs-sdl with
broken dependencies.
> Default STATIC for osdialog library

- src/cdogs/log.c
- src/cdogs/log.h
As described in the issue, this will solve issues when building with gcc10 (multiple definitions).
> Fix linker issues with gcc10 (fixes #658)

- missions/custom/techdemo/spawnertest.cdogscpn/campaign.json
- missions/custom/techdemo/spawnertest.cdogscpn/characters.json
- missions/custom/techdemo/spawnertest.cdogscpn/missions.json
- src/cdogs/pickup.c
Fixes issue #660
Added a check to see if the actor already has the gun to prevent spawning the currently equipped gun. Even though ActorReplaceGun returns early, current gun is still marked for replacement and a new pickup is spawned. 
This also changes how picking up a gun behaves when that gun is currently equipped. Before this change, the gun pickup was destroyed and spawned again. Now it does not spawn. This makes it the same as what happens when picking up the currently equipped gun when there's an open gun slot (the gun pickup is destroyed).
> Fix minor weapon pickup bug

- CMakeLists.txt
Hello!
On latest master, `cmake` shows this warning:
```
CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindOpenGL.cmake:305 (message):
Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
FindOpenGL found both a legacy GL library:
OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
and GLVND libraries for OpenGL and GLX:
OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first): …
```
> CMake: set CMP0072 to NEW

- src/proto/CMakeLists.txt
Hi,
When I was building cdogs-sdl I met an error, said 
``` cmd
c1 : fatal error C1083: Cannot open source file: 'D:\repos\thirdparty\cdogs-sdl\builds\src\proto\nanopb\pb_encode.c': N
o such file or directory [D:\repos\thirdparty\cdogs-sdl\builds\src\proto\cdogs_proto.vcxproj]
c1 : fatal error C1083: Cannot open source file: 'D:\repos\thirdparty\cdogs-sdl\builds\src\proto\nanopb\pb_common.c': N
o such file or directory [D:\repos\thirdparty\cdogs-sdl\builds\src\proto\cdogs_proto.vcxproj]
c1 : fatal error C1083: Cannot open source file: 'D:\repos\thirdparty\cdogs-sdl\builds\src\proto\msg.pb.c': No such fil
e or directory [D:\repos\thirdparty\cdogs-sdl\builds\src\proto\cdogs_proto.vcxproj]
c1 : fatal error C1083: Cannot open source file: …
```
> Remove set of cdogs_proto source files are genereated

- src/cdogs/handle_game_events.c
Addresses #774.
Brass shells were being created in two different places, when the player shoots and when the gun is reloaded. I went ahead and removed one of them.
> Remove duplicate creation of brass shells

- src/cdogs/yajl/yajl_buf.c
- src/cdogs/yajl/yajl_encode.c
- src/cdogs/yajl/yajl_tree.c
The modified copy of yajl contains some security issues that were fixed in Debian's yajl package (CVE-2017-16516, CVE-2022-24795, CVE-2023-33460).
See also:
https://security-tracker.debian.org/tracker/source-package/yajl
https://udd.debian.org/patches.cgi?src=yajl&version=2.1.0-5
> Security fixes for yajl

- src/cdogs/hud/player_hud.c
hi i added a line of code to make the arrows appear depending on the screensize. They are not right on the player but way more noticeable than before :) Hope you like the change!
> fixed arrows to be closer to the player

- downloads.html
This PR addresses [Issue 848](https://github.com/cxong/cdogs-sdl/issues/848) in the `gh-pages` branch of cdogs-sdl repo.
I added a new section, **Linux packages for cdogs-sdl**, which lists major Linux distributions that have `cdogs-sdl` packages available as well as package manager command examples of how to install `cdogs-sdl` for each Linux distro.
URL's to each distribution's package manager index entry for `cdogs-sdl` are included, but the links are intentionally version-agnostic to avoid the problem of stale links.
> Issue 848 - List of linux package managers where C-Dogs SDL is available
